### ISSUE TITLE
Defining plugin in `twind.config.js` breaking some utility classes

### ISSUE THREAD

**Issue by sibbng** [tw-in-js/twind-cli#2]
Reproduction https://github.com/sibbng/twind-cli-repro

git clone https://github.com/sibbng/twind-cli-repro
cd twind-cli-repro
yarn
yarn twind -o styles.css -b -w

`bg-gray-300` seems working fine but `mt-20` and `p-5` generated with `focus` variant. Which is only used for `btn` plugin in `twind.config.js`

**Comment by sastan** [comment]
Thanks! I'll look into it.

**Comment by sastan** [comment]
That repo helped a lot. Could you please try 0.2.0. I added a [limitations section](https://github.com/tw-in-js/twind-cli#limitations) (based on #1) maybe that helps.

**Comment by sibbng** [comment]
It works as expected. Thanks for quick fix.

**Comment by sibbng** [comment]
Hi, @sastan 

`btn` class generated perfectly as I confirmed. But another issue I mentioned before on Discord, changing config doesn't take effect while in watch mode still a thing.

`btn` class still exist in `styles.css` after removing it from plugins while twind in watch mode. 
Twind says `Loaded configuration from twind.config.js in 1 ms` but `btn` class doesnt disapper until I manually restart cli.

I'm on Windows 10.
